[bar.default]
background_opacity = 0.0
capsule = true
capsule_border = "on_secondary"
capsule_fill = "shadow"
capsule_foreground = "primary"
capsule_thickness = 0.99999998137354851
center = [ "workspaces", "media" ]
concave_edge_corners = false
end = [ "notifications", "network", "bluetooth", "volume", "tray", "battery" ]
font_family = "Hack Nerd Font Propo"
font_weight = 400
margin_ends = 0
padding = 5
panel_overlap = 0
radius = 0
scale = 0.90000000596046448
shadow = false
start = [ "control-center", "clock" ]
thickness = 22

    [bar.default.dead_zone.actions]
    right = "panel-toggle Not set"

[config]

[control_center]
show_session_button = false
show_shortcut_labels = false
sidebar_section = "none"

[desktop_widgets]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 564.0
    cy = 570.0
    output = "eDP-1"
    placement_height = 752.0
    placement_width = 1128.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
layer = "overlay"
show_actions = false

[shell]
app_icon_colorize = true
button_borders = false
font_family = "Hack"
input_borders = false
popup_borders = false

    [shell.launcher]
    categories = false
    show_app_origin_indicator = false
    show_icons = false

    [shell.panel]
    control_center_placement = "floating"
    launcher_placement = "attached"
    launcher_position = "top_left"
    open_near_click_control_center = true
    shadow = false

[templates]

[theme]
builtin = "Tokyo-Night"
community_palette = "Doomed"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "hyprland", "kitty" ]
    community_ids = [ "pywalfox", "discord", "neovim", "steam", "rofi", "fastfetch", "zathura", "yazi" ]

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.battery]
display_mode = "graphic"

[widget.control-center]
glyph = "brand-linqpad"

[widget.media]
max_length = 415

[widget.network]
color = "secondary"
icon_color = "tertiary"
show_label = false
